### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by ghost** [bmc/munkres#5] opened 2014-03-04 05:50 UTC
With munkres3 (Python 3 port) I get infinite loop when using sys.float_info.max values in the matrix.

**Comment by mika-fischer** [comment] 2016-01-22 22:24
The problem seems that when searching for the minimum in the matrix, minval is initialized with sys.maxsize, which is much much smaller that a lot of float values...

Maybe the following would work instead:
```python
    def __find_smallest(self):
        """Find the smallest uncovered value in the matrix."""
        minval = None
        for i in range(self.n):
            for j in range(self.n):
                if (not self.row_covered[i]) and (not self.col_covered[j]):
                    if minval is None or minval > self.C[i][j]:
                        minval = self.C[i][j]
        return minval if minval is not None else sys.maxsize
```

**Comment by mika-fischer** [comment] 2016-01-22 22:39
And the issue is also present with the original code. It's most apparent with very large values when using the 32bit version of Python.

For instance:
```python
from munkres import Munkres
matrix = [[5e17], [5e17]]
m = Munkres()
indexes = m.compute(matrix)
```

**Comment by bmc** [comment] 2017-06-27 17:19
Should be fixed.

**Closed by bmc** 2017-06-27 17:19 UTC
